## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [2]:
def divide(a,b):
    try:
        return a/b
    except ZeroDivisionError:
        print("You are trying to divide by '0'. That's not possible!!!")
        
divide(5,0)

You are trying to divide by '0'. That's not possible!!!


## ------------------------------------------------------------------------------------------------

Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [1]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
k=[print(i+' '+j+' '+k+'.') for i in subjects for j in verbs for k in objects]

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


## ------------------------------------------------------------------------------------------------

Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [8]:
import math
import numpy as np
def create_output_matrix(vector,n,increasing=False):
    l=[]
    k=[]
    if not increasing:
        
        for j in range(n-1,-1,-1):
            m=[int(math.pow(i,j)) for i in vector]
            l.append(m)
        
        for i in range(len(vector)):
            m=[l[j][i] for j in range(n)]
            k.append(m)
            
        mat=np.array(k).reshape(len(vector),n)
        print("When incresing = False, the matrix is\n",mat)
        
    elif increasing:
        
        for j in range(n):
            m=[int(math.pow(i,j)) for i in vector]
            l.append(m)
          
        for i in range(len(vector)):
            m=[l[j][i] for j in range(n)]
            k.append(m) 
            
        mat=np.array(k).reshape(len(vector),n)
        print("When incresing = True, the matrix is\n",mat)

inputs=input('Enter input vector in comma seperated : ')
inputs=inputs.split(',')
put=[int(item) for item in inputs]
no_columns=int(input("How many columns required : "))
create_output_matrix(put,no_columns,False)
create_output_matrix(put,no_columns,True)



Enter input vector in comma seperated : 1,2,4,6,8,10
How many columns required : 5
When incresing = False, the matrix is
 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]]
When incresing = True, the matrix is
 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]]
