# Subjective Assignment - 5 - Numpy 1

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [1]:
import numpy as np

In [21]:
oa=np.ones((5,5),dtype=int)+5
print("Original Array \n",oa)
oa[1:-1,1:-1]=0
print("6 on the border and 0 inside in the array-\n",np.mat(oa))

Original Array 
 [[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
6 on the border and 0 inside in the array-
 [[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


## -------------------------------------------------------------------------------------------------

Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [20]:
ch=np.ones([8,8],dtype=int)
ch[::2,::2],ch[1::2,::2]=3,9
ch[::2,1::2],ch[1::2,1::2]=9,3
print("Checkerboard pattern-\n",np.mat(ch))

Checkerboard pattern-
 [[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


## -------------------------------------------------------------------------------------------------

Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [32]:
ea=np.empty([3,4],dtype=int)
print("Empty array :\n",ea)
fa=np.full([3,3],6)
print("Full array :\n",fa)


Empty array :
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Full array :
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


## -------------------------------------------------------------------------------------------------

Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [40]:
f=np.array([0,12,45.21,34,99.91])
print("Values in Fahrenheit degrees-\n",f)
c=(5*(f-32))/9
print("Values in Centigrade degrees-\n",c)

Values in Fahrenheit degrees-
 [ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees-
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## -------------------------------------------------------------------------------------------------

Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [53]:
cn=np.array([1+0j,0.70710678+0.70710678j])
print("Original array : ",cn)
print("Real part of the array-\n",cn.real)
print("Imaginary part of the array-\n",cn.imag)

Original array :  [1.        +0.j         0.70710678+0.70710678j]
Real part of the array-
 [1.         0.70710678]
Imaginary part of the array-
 [0.         0.70710678]


## -------------------------------------------------------------------------------------------------

Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [63]:
a1=np.array([0,10,20,40,60])
print("Array1: ",a1)
a2=np.array([0,40])
print("Array2: ",a2)
oa=np.in1d(a1,a2)
print("Compare each element of array1 and array2\n",oa)

Array1:  [ 0 10 20 40 60]
Array2:  [ 0 40]
Compare each element of array1 and array2
 [ True False False  True False]


## -------------------------------------------------------------------------------------------------

Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [66]:
a1=np.array([0,10,20,40,60])
print("Array1: ",a1)
a2=np.array([10,40])
print("Array2: ",a2)
common=np.intersect1d(a1,a2)
print("Common values between two arrays-\n",common)

Array1:  [ 0 10 20 40 60]
Array2:  [10 40]
Common values between two arrays-
 [10 40]


## -------------------------------------------------------------------------------------------------

Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [75]:
a1=np.array([10,10,20,20,30,30])
print("Original array-\n",a1)
uq1=np.unique(a1)
print("Unique elements of the above array-\n",uq1)
a2=np.array([[1,1],[2,3]])
print("Original array-\n",a2)
uq2=np.unique(a2)
print("Unique elements of the above array-\n",uq2)

Original array-
 [10 10 20 20 30 30]
Unique elements of the above array-
 [10 20 30]
Original array-
 [[1 1]
 [2 3]]
Unique elements of the above array-
 [1 2 3]


## -------------------------------------------------------------------------------------------------

Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [77]:
a1=np.array([0,10,20,40,60,80])
a2=np.array([10,30,40,50,70])
uv=np.setxor1d(a1,a2)
print("Array1- ",a1)
print("Array2- ",a2)
print("Unique values that are in only one (not both) of the input arrays-\n",uv)

Array1-  [ 0 10 20 40 60 80]
Array2-  [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays-
 [ 0 20 30 50 60 70 80]


## -------------------------------------------------------------------------------------------------

Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [83]:
a=np.array([544,65,2655,840,0])
b=np.array([1,2,3,4,5,6,7,8,9])
print(a,np.all(a))
print(b,np.all(b))

[ 544   65 2655  840    0] False
[1 2 3 4 5 6 7 8 9] True


## -------------------------------------------------------------------------------------------------

Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [89]:
a=np.array([[544,65,26,0],[0,24,12,56],[25,87,65,45]])
print(a,np.all(a,axis=1))
print(a,np.all(a,axis=0))
print(a,np.all(a))

[[544  65  26   0]
 [  0  24  12  56]
 [ 25  87  65  45]] [False False  True]
[[544  65  26   0]
 [  0  24  12  56]
 [ 25  87  65  45]] [False  True  True False]
[[544  65  26   0]
 [  0  24  12  56]
 [ 25  87  65  45]] False


## -------------------------------------------------------------------------------------------------

Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [92]:
array=np.array([1,2,3,4])
print("Original array\n",array)
array2t=np.tile(array,2)
print("Repeating 2 times\n",array2t)
array3t=np.tile(array,3)
print("Repeating 3 times\n",array3t)

Original array
 [1 2 3 4]
Repeating 2 times
 [1 2 3 4 1 2 3 4]
Repeating 3 times
 [1 2 3 4 1 2 3 4 1 2 3 4]


## -------------------------------------------------------------------------------------------------

Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [93]:
array=np.array([1,2,3,4,5,6])
print("Original array : ",array)
print("Maximum value index - ",np.argmax(array))
print("Minimum value index - ",np.argmin(array))

Original array :  [1 2 3 4 5 6]
Maximum value index -  5
Minimum value index -  0


## -------------------------------------------------------------------------------------------------

Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [100]:
a=np.array([1,2])
b=np.array([4,5])
print("Array a- ",a)
print("Array b- ",b)
print("a > b")
print(a>b)
print("a >= b")
print(a >= b)
print("a < b")
print(a<b)
print("a <= b")
print(a<=b)

Array a-  [1 2]
Array b-  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


## -------------------------------------------------------------------------------------------------

Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [103]:
a=np.array([[4,6],[2,1]])
print("Original array:\n",a)
s0=np.sort(a,axis=0)
print("Sort along the first axis:\n",s0)
sl=np.sort(s0,axis=1)
print("Sort along the last axis-\n",sl)

Original array:
 [[4 6]
 [2 1]]
Sort along the first axis:
 [[2 1]
 [4 6]]
Sort along the last axis-
 [[1 2]
 [4 6]]


## -------------------------------------------------------------------------------------------------

Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [114]:

first_names = np.array(['Margery','Betsey','Shelley','Lanell','Genesis'])
last_names = np.array(['Woolum','Battle','Plotner','Brien','Stahl'])
sort = np.lexsort((first_names, last_names))
print("First Names\n",first_names)
print("Last Names\n",last_names)
print(sort)


First Names
 ['Margery' 'Betsey' 'Shelley' 'Lanell' 'Genesis']
Last Names
 ['Woolum' 'Battle' 'Plotner' 'Brien' 'Stahl']
[1 3 2 4 0]


## -------------------------------------------------------------------------------------------------

Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [108]:
a=np.array([[0,10,20],[20,30,40]])
print("array\n",a)
print("Values bigger than 10 = ",a[a>10])
print("Theie indices are ",np.where(a>10))

array
 [[ 0 10 20]
 [20 30 40]]
Values bigger than 10 =  [20 20 30 40]
Theie indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


## -------------------------------------------------------------------------------------------------

Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [113]:
a=np.ones((4,4))
print("Array\n",a)
size=a.size*a.itemsize
print(f'{size} bytes')

Array
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
128 bytes


## Great Job!